**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.array([1,2,3])

**TASK:** define (2 x 2) matrix 'A' 


In [16]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

**TASK:** define (2 x 2) matrix 'B'

In [17]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

**TASK:** check the type of 'x'

In [5]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [6]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [9]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [10]:
A.shape

(2, 2)

**TASK:** 

In [ ]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [11]:
def have_same_shape(array_1, array_2):
    if array_1.shape == array_2.shape:
        return True
    else:
        print('Arrays must have same shape!')
        return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [12]:
have_same_shape(A, x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [13]:
have_same_shape(A, B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [14]:
def matrix_addition(A, B):
    if have_same_shape(A,B):
        C = A+B
        return C

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [15]:
matrix_addition(A, B)

array([[ 6,  8],
       [10, 12]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [37]:
lst_of_arr = [A,A,B,B,B]
lst_of_arr[0].shape
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
def multiple_matrix_addition(lst_of_arr):
    NEW_ARRAY = np.zeros(lst_of_arr[0].shape)
    for arr in lst_of_arr:
        NEW_ARRAY = matrix_addition(NEW_ARRAY, arr)       
    return NEW_ARRAY

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [41]:
multiple_matrix_addition([A,A,B,B,B])

array([[17., 22.],
       [27., 32.]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [42]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
y = np.zeros((5,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
numOfColumns = np.size(x,1)
numOfColumns

3

In [63]:
def can_multiply(array_a, array_b):
    if np.size(array_a,1)==np.size(array_b,0):
        print(np.matmul(array_a,array_b))
        return True
    else:
        print('Matrices can not be multiplied.')
        return False
        

In [64]:
can_multiply(x,y)

Matrices can not be multiplied.


False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [65]:
can_multiply(A,B)

[[19 22]
 [43 50]]


True

In [66]:
A

array([[1, 2],
       [3, 4]])

In [67]:
B

array([[5, 6],
       [7, 8]])

**TASK:**  define matrix (3 x 2) matrix C

In [71]:
C = np.ones((3,2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [69]:
can_multiply(A,C)

Matrices can not be multiplied.


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [70]:
can_multiply(C,A)

[[4. 6.]
 [4. 6.]
 [4. 6.]]


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [77]:
def matrix_multiplication(array_a, array_b):
    if can_multiply(array_a, array_b) == True:
        return np.matmul(array_a, array_b)

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [78]:
matrix_multiplication(C,B)

[[12. 14.]
 [12. 14.]
 [12. 14.]]


array([[12., 14.],
       [12., 14.],
       [12., 14.]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [79]:
matrix_multiplication(A,C)

Matrices can not be multiplied.
