# Basic Operations with Matrices

In [2]:
import numpy as np

### Creating Vectors & Matrices with Numpy

In [3]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [4]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
type(x)

numpy.ndarray

In [6]:
type(A)

numpy.ndarray

### Shape

In [7]:
A.shape

(3, 2)

In [8]:
x.shape

(4,)

In [9]:
len(x)

4

In [12]:
Y = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
Y

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [13]:
Y.shape

(1, 1, 3, 3)

### Transposition of a Matrix

In [10]:
A_T = A.T
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
A_T = A.transpose()

In [12]:
A_T.shape

(2, 3)

### Matrix Addition

In [13]:
B = np.array([[2,5],[7,4],[4,3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [14]:
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [15]:
D = A + 1
D

array([[2, 3],
       [4, 5],
       [6, 7]])

### Matrix Multiplication

In [19]:
A = np.array([[1,2],[3,4],[5,6]])

In [20]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
B = np.array([[2],[4]])

In [17]:
B

array([[2],
       [4]])

In [18]:
C = np.dot(A,B)
C

array([[10],
       [22],
       [34]])

In [21]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [23]:
C.shape

(3, 1)

### Identity Matrices

In [24]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Determinant

In [26]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [27]:
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

In [28]:
M = np.array([[1,2],[3,4],[5,6]])
det_M = np.linalg.det(M)
det_M

LinAlgError: Last 2 dimensions of the array must be square

### Inverse Matrices

In [19]:
A = np.array([[3,0,2],[2,0,-2],[0,1,1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [20]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [21]:
I = A_inv.dot(A)

In [22]:
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [25]:
A.mean()

0.7777777777777778