In [1]:
import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.0 0.0


ZeroDivisionError: float division by zero

In [2]:
import numpy as np
from timeit import Timer

size_of_vec = 1000
X_list = range(size_of_vec)
Y_list = range(size_of_vec)
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)

def pure_python_version():
    Z = [X_list[i] + Y_list[i] for i in range(len(X_list)) ]

def numpy_version():
    Z = X + Y

timer_obj1 = Timer("pure_python_version()", 
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", 
                   "from __main__ import numpy_version")

print(timer_obj1.timeit(10))
print(timer_obj2.timeit(10))  # Runs Faster!

print(timer_obj1.repeat(repeat=3, number=10))
print(timer_obj2.repeat(repeat=3, number=10)) # repeat to prove it!

0.0024700000000024147
0.00030550000000317823
[0.0025063999999943576, 0.0023014999999944052, 0.0024711999999951217]
[4.17000000041412e-05, 0.000595400000001689, 1.3200000005042511e-05]


# Load in NumPy

In [3]:
import numpy as np

# The Basics

In [30]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [20]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [21]:
# Get Dimension
b.ndim

2

In [22]:
# Get Shape
b.shape #b has 2 rows, 3 columns

(2, 3)

In [36]:
# Get Type
b.dtype

dtype('float64')

In [37]:
# Get Size
b.itemsize #shows number of bytes per item in array

8

In [40]:
# Get Total Size
b.nbytes
b.size * b.itemsize #shows total number of bytes by multiplying the number of bytes per item*number of items

48

In [10]:
import numpy as np
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c.shape

(2, 2, 3)

In [11]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
c.dtype

dtype('int32')

In [13]:
c.itemsize

4

In [15]:
c.nbytes

48

# Accessing / Changing specific elements, rows, columns, etc.

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [22]:
# Get a specific element [r,c] #indexing starts at 0 - row 2 is at index 1 and column 6 is at index 5
a[1,5]

13

In [24]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [25]:
# Get a specific column
a[:,1]

array([2, 9])

In [55]:
# Getting a little more fancy [startindex:endindex:stepsize] - get every other item in first row, starting at 2
a[0,1:6:2] # or a[0,1:-1:2]

array([2, 4, 6])

In [31]:
a[::-1,6]

array([14,  7])

In [56]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [57]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [58]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
a[1,:]=[6]
print(a)

[[1 2 3 4 5 6 1]
 [6 6 6 6 6 6 6]]


*3-d example

In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element (work outside in) [set,row,column]
# Get the 4 by accessing the first set (index 0), the second row (index 1), the second element(index 1)
b[0,1,1]

4

In [37]:
b[1,0,0]

5

In [38]:
b[1,0,1]

6

In [39]:
# Get both sets, all of second row
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [40]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [65]:
# Get both sets, all of second column
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [73]:
# replace - make sure the replacement is the same shape
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [43]:
b[:,:,0] = [[1,2],[3,4]]
b

array([[[1, 2],
        [2, 4]],

       [[3, 6],
        [4, 8]]])

In [44]:
b.ndim

3

# Initializing Different Types of Arrays

In [74]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [75]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [76]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [77]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [51]:
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [79]:
# Any other number(full_like)
# take the shape of a, and fill with 4s
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [81]:
# Random decimal numbers
np.random.rand(2,4,2)

array([[[0.79743321, 0.8397553 ],
        [0.96868459, 0.32113845],
        [0.24910495, 0.54904013],
        [0.24582925, 0.66048549]],

       [[0.18402687, 0.84960673],
        [0.28212778, 0.87161638],
        [0.70166038, 0.6269491 ],
        [0.81380281, 0.88505904]]])

In [52]:
np.random.rand(3,2,2)

array([[[0.76361438, 0.97015571],
        [0.07812514, 0.22163125]],

       [[0.99931705, 0.21336018],
        [0.9871725 , 0.48976972]],

       [[0.91154893, 0.9074731 ],
        [0.06590686, 0.27014695]]])

In [55]:
# Random Integer Values
np.random.randint(4,7, size=(3,3))

array([[4, 6, 6],
       [5, 6, 6],
       [6, 6, 6]])

In [53]:
np.random.randint(1,10,size=(2,2,2))

array([[[1, 9],
        [3, 4]],

       [[3, 7],
        [8, 8]]])

In [56]:
# The identity matrix - produces a square matrix - argument indicates the number of rows and columns
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [57]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [102]:
# Repeat an array
arr = np.array([[1,2,3,]])
r1 = np.repeat(arr,3,axis=0) # axis = 0 refers to the rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
arr1 = np.array([[1,2]])
r2 = np.repeat(arr1,4,axis=1) # axis = 1 refers to the columns
print(r2)

[[1 1 1 1 2 2 2 2]]


In [71]:
arr2 = np.array([[1,2],[1,2]])
r3 = np.repeat(arr2,2,axis=1)
r3

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

In [98]:
w = np.ones((5,5))

In [99]:
print(w)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
w[1:4,1:4]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
w[1:4,1:4]=np.zeros((3,3))

In [102]:
print(w)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [112]:
w[2,2]

0.0

In [118]:
w[2,2] = 9
print(w)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
x[1:4,1:4] = np.ones((3,3))
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [122]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [4]:
# b is just pointing to the same array as a, so changing b changes a
import numpy as np
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [6]:
# to make a copy of the contents of a:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [76]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a + 2

array([3, 4, 5, 6])

In [10]:
a - 2

array([-1,  0,  1,  2])

In [11]:
a * 2

array([2, 4, 6, 8])

In [12]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [15]:
a = np.array([1,2,3,4])
a += 2
a

array([3, 4, 5, 6])

In [17]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [18]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [19]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [21]:
a = np.ones((2,3))

In [22]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [24]:
#can do matrix multplication because number of rows in first set match number of columns in second set, and number of columns in first set match number of rows in second set

In [25]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [27]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [28]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats, axis = 0) # minimum element in each column

array([1, 2, 3])

In [43]:
np.max(stats, axis = 1) # maximum element in each row

array([3, 6])

In [44]:
np.sum(stats) #sums all elements in matrix

21

In [45]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [46]:
np.sum(stats, axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [49]:
print(before.shape)

(2, 4)


In [50]:
after = before.reshape((8,1))

In [51]:
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [54]:
after = before.reshape((2,2,2)) #can reshape into any shape with 8 elements

In [55]:
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [61]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [65]:
# Horizontal Stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### Load Data from File

In [68]:
filedata = np.genfromtxt('Numpy_dataset.txt',delimiter=',')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [79]:
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

### Boolean Masking and Advanced Indexing

In [80]:
filedata > 15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [81]:
filedata[filedata > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [77]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [84]:
np.any(filedata > 25, axis = 0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [88]:
np.all(filedata > 2, axis = 0) # looking for all elements in a column to meet the condition

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [89]:
np.all(filedata > 2, axis = 1)

array([False,  True,  True])

In [91]:
((filedata >10) & (filedata <20))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [93]:
(~(filedata >10) & (filedata <20)) #reverse of above

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [94]:
a[2:4,0:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [95]:
a[[0,1,2,3],[1,2,3,4]]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [96]:
a[[0,4,5],3:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed