# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [6]:
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
d = np.random.randint(0,9, size=(3,3))
d

array([[5, 1, 4],
       [6, 8, 0],
       [8, 8, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
e = np.array([1,2,0,0,4,0])
indices = np.where(e>0)
indices

(array([0, 1, 4], dtype=int64),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [24]:
f = np.random.rand(3,3,3)
f

array([[[0.14144196, 0.29463498, 0.21549459],
        [0.33789708, 0.25314443, 0.17327213],
        [0.11711752, 0.80811526, 0.50338867]],

       [[0.09766354, 0.77786017, 0.19202694],
        [0.84868588, 0.03881183, 0.84747322],
        [0.67093116, 0.54963878, 0.40970874]],

       [[0.26856651, 0.09634659, 0.69529564],
        [0.40829953, 0.34916161, 0.45350355],
        [0.48233446, 0.12417913, 0.44773382]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
g = np.random.rand(10,10)
g

array([[0.57516742, 0.94838365, 0.76141049, 0.54629846, 0.75252066,
        0.00481089, 0.43900219, 0.84288413, 0.82561856, 0.87374461],
       [0.7014366 , 0.42084482, 0.53592858, 0.15153808, 0.22306519,
        0.092108  , 0.40596512, 0.50535897, 0.04151204, 0.37954453],
       [0.59292994, 0.20075277, 0.50823401, 0.54312126, 0.86852893,
        0.50007116, 0.4587808 , 0.64341225, 0.05984347, 0.48757735],
       [0.04644804, 0.25154332, 0.36372011, 0.37368789, 0.89439532,
        0.70107416, 0.51336853, 0.54013863, 0.59634062, 0.7354069 ],
       [0.18453906, 0.93245099, 0.32377719, 0.51781284, 0.08218151,
        0.13490966, 0.40388137, 0.78672498, 0.10127062, 0.79209342],
       [0.69342384, 0.44591591, 0.26168994, 0.51197256, 0.98011389,
        0.55113819, 0.73886711, 0.84534954, 0.09866974, 0.18772579],
       [0.84555782, 0.30854309, 0.74058289, 0.03738526, 0.45427939,
        0.41467569, 0.02890145, 0.0733632 , 0.79524294, 0.80847333],
       [0.04093876, 0.22294211, 0.7330371

In [30]:
print(np.min(g))
print(np.max(g))

0.008895627163586828
0.9994855797151283


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [10]:
h = np.random.rand(30)
h

array([0.12375004, 0.85919678, 0.38371292, 0.31609976, 0.06609884,
       0.75653428, 0.95289616, 0.95011209, 0.4929017 , 0.82698621,
       0.05574616, 0.59130983, 0.00155472, 0.78625244, 0.88639531,
       0.5662789 , 0.82791101, 0.90087323, 0.48896221, 0.95401793,
       0.14481875, 0.30624746, 0.40678693, 0.43997046, 0.43699886,
       0.57242947, 0.38949716, 0.98622005, 0.24578036, 0.04206775])

In [11]:
np.mean(h)

0.5252802594591809

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
i = np.ones((4,6))
i

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
i[1:3,1:5]=0
i

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
i.shape

(4, 6)

In [24]:
j = np.zeros((6,8))
j[1:5,1:7]=i
j

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
0 * np.nan

nan

In [35]:
np.nan == np.nan

False

In [36]:
np.inf > np.nan

False

In [37]:
np.nan - np.nan

nan

In [38]:
np.nan in set([np.nan])

True

In [39]:
0.3 == 3 * 0.1

False

In [40]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [44]:
k = np.zeros((5,5))
k[[1,2,3,4],[0,1,2,3]]=[1,2,3,4]
k

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [54]:
l = np.random.randint(1,100,size=((6,7,8)))
np.unravel_index(100-1,l.shape)

(1, 5, 3)

In [57]:
l

array([[[48, 11, 53, 23, 26, 37, 79, 94],
        [92, 59, 25,  9, 85, 97, 67, 26],
        [40,  5, 89, 80, 86, 31, 84, 30],
        [78, 81, 99,  7, 74, 51, 65,  1],
        [17,  5, 24, 33, 81, 56, 57, 12],
        [ 1, 65, 50, 19, 39, 89, 75, 61],
        [68, 97, 13, 37, 58, 83, 89, 63]],

       [[72, 84, 73, 89, 52, 76, 81, 43],
        [97, 62, 90, 84, 91, 13, 68, 64],
        [62, 96, 99, 95, 80, 13, 51, 17],
        [67, 17, 49, 92, 21, 80, 87, 69],
        [83,  6, 13, 74, 55, 34, 33, 90],
        [48, 12, 26, 47, 42, 23, 69, 16],
        [48, 94, 32,  3, 97, 79, 56, 51]],

       [[91, 49, 31, 95, 42, 46, 13, 83],
        [12, 19, 20, 15, 22, 15, 76, 31],
        [85, 73, 92, 61, 36, 23, 59, 52],
        [ 4, 76, 27, 44, 29,  8, 45, 98],
        [65, 26, 63, 19,  7, 14, 10, 41],
        [48,  8, 82, 66, 20, 69, 89, 27],
        [64, 69, 68, 77, 85, 59, 86, 39]],

       [[85, 79, 87, 43, 15, 44, 69, 72],
        [26, 45, 46,  3, 59, 47, 96, 71],
        [34, 46, 77, 67, 81,

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [70]:
m = np.random.randint(25,size=(5,5))
m

array([[16, 21,  0,  5, 19],
       [ 1, 20,  3,  0, 11],
       [ 5, 14, 22, 21,  1],
       [ 1, 22, 12, 10, 23],
       [ 0, 19, 12, 11, 13]])

In [71]:
mmax, mmin = m.max(), m.min()
m = (m-mmin)/(mmax - mmin)
print(m)

[[0.69565217 0.91304348 0.         0.2173913  0.82608696]
 [0.04347826 0.86956522 0.13043478 0.         0.47826087]
 [0.2173913  0.60869565 0.95652174 0.91304348 0.04347826]
 [0.04347826 0.95652174 0.52173913 0.43478261 1.        ]
 [0.         0.82608696 0.52173913 0.47826087 0.56521739]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [77]:
n = np.arange(10)
negate = np.where((n > 3) & (n < 8),n*-1,n)
negate

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 18. How to round away from zero a float array ? (★☆☆)

In [101]:
p = np.array([10.456,0.123,7.89,-1.2])
p

array([10.456,  0.123,  7.89 , -1.2  ])

In [102]:
p_round_away_from_zero = np.copysign(np.ceil(np.abs(p)),p)
p_round_away_from_zero

array([11.,  1.,  8., -2.])

#### 19. Find common values between two arrays? (★☆☆)

In [110]:
q1 = np.arange(1,10)
q2 = np.arange(5,15)

print(q1)
print(q2)

[1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [112]:
common_values = np.intersect1d(q1,q2)
common_values

array([5, 6, 7, 8, 9])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [113]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\jess-\AppData\Local\Temp\ipykernel_20908\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [115]:
np.sqrt(-1)

C:\Users\jess-\AppData\Local\Temp\ipykernel_20908\3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [116]:
np.emath.sqrt(-1)

1j

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [125]:
r = np.random.randint(50,100,size=(2,5))
r

array([[77, 81, 66, 89, 62],
       [53, 56, 78, 79, 96]])

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [129]:
s = np.linspace(0,1,12)[1:-1]
s

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [153]:
t = np.random.random(10)
np.sort(t)

array([0.0534987 , 0.27960246, 0.29249847, 0.29986658, 0.40679353,
       0.56733772, 0.6574514 , 0.73916535, 0.74379699, 0.76393426])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [178]:
A = np.random.random(10)
B = np.random.random(10)
A==B

array([False, False, False, False, False, False, False, False, False,
       False])

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [174]:
u = np.random.random(10)
u

array([0.91053804, 0.60991643, 0.03663425, 0.83634794, 0.18072379,
       0.55307725, 0.07570256, 0.47758166, 0.26648675, 0.83154782])

In [175]:
u[np.where(u==np.amax(u))] = 0
u

array([0.        , 0.60991643, 0.03663425, 0.83634794, 0.18072379,
       0.55307725, 0.07570256, 0.47758166, 0.26648675, 0.83154782])

#### 26. Find the closest value to random element in a vector? (★★☆)

In [179]:
def find_nearest(array,value):
    array = np.asarray(array)
    idx = (np.abs(array-value)).argmin()
    return array[idx]

array = np.random.random(10)
print(array)

[0.95072842 0.30502953 0.07354116 0.3625896  0.18901743 0.37406732
 0.27259857 0.98489618 0.54693488 0.47216303]


In [180]:
find_nearest(array,.5)

0.4721630322589164

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [182]:
w = np.array([1.2,3.56,4,78],dtype = 'int32')
w

array([ 1,  3,  4, 78])

#### 28. Sort an array by the nth column? (★★☆)

In [193]:
x = np.random.randint(50,size=(3,5))
x

array([[49,  7, 17, 24, 42],
       [30, 34, 45, 19, 43],
       [24, 40, 12, 31, 13]])

In [194]:
x[x[:,4].argsort()] #sort by column 4

array([[24, 40, 12, 31, 13],
       [49,  7, 17, 24, 42],
       [30, 34, 45, 19, 43]])

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [202]:
y = np.random.randint(0,5,(2,10))
print(y)
print((~y.any(axis=0)).any())

[[0 2 2 4 4 1 0 0 0 1]
 [1 1 2 1 2 1 0 1 3 3]]
True


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [236]:
z = np.array([1,2,3,4,5])
nz = 3
z_0 = np.zeros(len(z)+(len(z)-1)*(nz))
z_0[::nz+1] = z
print(z_0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [247]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a[[0,1]]=a[[1,0]]
a

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

#### 32. How to negate a boolean value inside an array? (★★★)

In [253]:
a = np.array([True, False, True, True])
a

array([ True, False,  True,  True])

In [254]:
~a

array([False,  True, False, False])

#### 33. Find the most frequent value in an array?

In [260]:
b = np.random.randint(1,10,10)
b

array([9, 9, 6, 8, 4, 2, 6, 7, 3, 9])

In [265]:
np.bincount(b) #there are 10 bins numbered 0-9; the elements in the array show how many occurences of each bin number there are (no zeros, no ones, 1 two, 1 three, etc.) 

array([0, 0, 1, 1, 1, 0, 2, 1, 1, 3], dtype=int64)

In [266]:
np.bincount(b).argmax() #returns the bin number with the highest value

9

#### 34. Get the n largest values of an array (★★★)

In [272]:
c = np.random.randint(0,10,10)
c

array([9, 4, 7, 5, 6, 6, 3, 5, 1, 8])

In [277]:
sorted_index_array = np.argsort(c)
sorted_array = c[sorted_index_array]
sorted_array

array([1, 3, 4, 5, 5, 6, 6, 7, 8, 9])

In [279]:
n=3
n_largest = sorted_array[-n:]
n_largest[0]
print(n_largest)

[7 8 9]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [282]:
d = np.array([[1,2,3,4],[0,0,0,0],[5,6,7,8],[0,0,0,0]])
d

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

In [284]:
unique_rows = np.unique(d,axis=0)
unique_rows

array([[0, 0, 0, 0],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [287]:
import numpy

In [288]:
numpy.random.randint([1,2,3])

array([0, 0, 1])